export const categoryBannerAdImagedata = {
    ApplePears:"https://www.shutterstock.com/shutterstock/photos/2350073779/display_1500/stock-photo-apples-pears-and-plums-in-baskets-on-a-sunny-wooden-table-thanksgiving-background-village-2350073779.jpg",
    AvacadoPeachPlum:"https://www.shutterstock.com/shutterstock/photos/1485097691/display_1500/stock-vector-pear-avocado-peach-fresh-fruits-and-splashes-d-realistic-vector-icon-set-1485097691.jpg",
    BananaMelonCoconut:"https://www.shutterstock.com/shutterstock/photos/1944860752/display_1500/stock-photo-summer-fruit-shopping-background-eco-friendly-shopping-bag-full-of-fresh-tropical-fruits-on-1944860752.jpg"
    ,
    CherriesBerriesDragonfruit:"https://c8.alamy.com/comp/2HWNNYY/fruit-bannerpeaches-cherries-apricots-red-currants-raspberries-and-leaves-isolated-on-blue-backgroundfruit-and-berry-banner-fruits-and-berries-2HWNNYY.jpg",
    CitrusMangosGrapes:"https://c8.alamy.com/comp/2C3J76Y/banner-with-green-fruits-on-a-green-background-with-free-space-for-text-composition-of-bunches-of-grapes-apples-mango-and-llime-falling-down-3d-re-2C3J76Y.jpg",
    Dates:"https://img.freepik.com/premium-photo/traditional-ramadan-kareem-snack-iftar-suhoor-ripe-dates-orange-background-sweet-arabian_908985-36219.jpg?w=740",
    GiftAssortedXlPacks:"https://img.freepik.com/premium-photo/concept-tropical-new-year-celebration_336355-1027.jpg?w=740",
    PomegranatePapayaPineapple:"https://img.freepik.com/premium-photo/pineapple-healthy-fruits-wonderful-pineapple-juice_843175-8205.jpg?w=740",
    SeasonalMinorFruits:"https://img.freepik.com/premium-photo/guava-fruit-with-leaf-black-background_978921-167.jpg?w=740",
    BagsTravelLuggages:"https://img.freepik.com/premium-photo/rad-luggage-let-s-discover-world-style_971713-379.jpg?w=900",
    juniorboy:"https://www.jiomart.com/images/category/519/junior-boys-20200831.jpg",
    juniorgirl:"https://www.jiomart.com/images/category/541/junior-girls-20200831.jpg",
    infants:"https://www.jiomart.com/images/category/550/infants-20200831.jpg",
    men:"https://www.jiomart.com/images/category/496/men-20200831.jpg",
    women:"https://www.jiomart.com/images/category/493/women-20200831.jpg",
    makeup:"https://www.shutterstock.com/image-photo/makeup-professional-cosmetics-on-pink-600nw-1398700589.jpg",
    skincare:"https://img.freepik.com/premium-vector/makeup-brush-banner_87720-1977.jpg?w=900"
}